### ISSUE TITLE
코드 개선에 대한 질문 (개인 1주차)

### ISSUE THREAD

**Issue by nayoung3669** [nayoung3669/todolist_react#1]
안녕하세요. todo list 기능을 구현한 후 컴포넌트 구성과 렌더링 최적화에 대해 의문점이 생겨 이슈를 남기게 되었습니다.

1. 현재 App 컴포넌트에서 TodoTemplate 컴포넌트를 렌더링해주고 있고, TodoTemplate의 children으로 TodoInput 컴포넌트와 TodoList 컴포넌트가 있습니다. 즉 TodoTemplate에서 Layout 역할을 해주고 있습니다. 그리고 마지막으로 TodoList에서 map()을 사용하여 TodoItem을 보여주고 있습니다. 

  ㄴ TodoTemplate.js
    ㄴ TodoInput.js
    ㄴ TodoList.js
      ㄴ TodoItem.js

어떻게 하면 컴포넌트를 더욱 효율적이고, 재사용 가능하도록 작성할 수 있는지 더 생각이 나지 않아 질문드립니다. 

2. 현재 React.memo와 useCallback hook으로 렌더링 최적화를 구현하고 있습니다. TodoList와 TodoItem에서 React.memo를 사용해주고 있습니다. App.js에서 onAdd, onRemove, onToggle 메소드를 선언했는데 여기서 각각 함수에 useCallback을 적용해 함수를 재사용하도록 만들어주고 있습니다. 

제가 잘 사용한 것이 맞는지, 그리고 어떤 최적화 방법을 더 사용할 수 있는지 궁금하여 질문드립니다. 특히 React.memo는 props 가 변경되지 않을 때 연산된 값을 재사용한다고 알고있는데 그렇다면 제가 만든 컴포넌트에도 더 사용할 수 있는지, 제가 이해한 부분이 맞는지 궁금합니다.

추가적인 피드백 사항이 있다면 남겨주시면 감사하겠습니다!

읽어주셔서 감사합니다 :)

**Comment by skdud4659** [comment]
안녕하세요 나영님:)

1. 해당 부분은 지난번 순회 이후로 반복되는 부분은 많이 수정된 것 같습니다.
컴포넌트를 나누는 기준은 개발자마다 다르고 그 기준이 명확하지 않지만 [시멘틱적인 로직 구성, 반복되는 코드 수정, 가독성] 세가지는 기본으로 많이 고려되면 좋습니다.

현재 작성해주신 구조는 저는 현재 프로젝트의 사이즈에서는 개인적으로 많이 개선되었다고 생각하며 input, button 등과 같은 요소들은 프로젝트의 스코프가 커지면서 계속 반복되는 요소이기 때문에 Element로 구분하시어 반복되는 부분을 재사용해도 좋습니다.

2. useCallback과 memo에 대해서는 쓰임새를 이해하고 있으신 부분이 맞는 것 같습니다.
렌더링 최적화와 관련된 부분은 코드와 글만으로는 다 파악이 어렵기 때문에 React DevTools을 사용해서 확인해보시면 좋을 것 같아요.
해당 툴을 이용해서 불필요하게 바뀌고 반복되는 부분이 없는지 파악하여 수정해 보시는 것을 권하며
렌더링 최적화도 중요하지만 코드의 가독성도 항상 고려하여 개발하시길 바랍니다.
